### ISSUE TITLE
Impossible de poster un commentaire

### ISSUE THREAD

**Issue by blogmotion** [comptoirsecu/csec-hugo#11]
Le commentaire ne part pas, en mode console F12 on peut voir ceci (vivaldi) : 
`XMLHttpRequest cannot load https://isso.infosecgur.us/new?uri=%2Fannonce%2Fbienvenue-sur-le-nouveau-site-du-comptoir-s%C3%A9cu%2F. Response to preflight request doesn't pass access control check: The 'Access-Control-Allow-Origin' header has a value 'http://csec.infosecgur.us/' that is not equal to the supplied origin. Origin 'https://www.comptoirsecu.fr/' is therefore not allowed access.`

**Comment by Astorsoft** [comment]
Merci beaucoup @blogmotion ! Pour la petite histoire le moteur de commentaire tourne sur isso.infosecgur.us, et le site "de test" était sur csec.infosecgur.us, j'avais oublié de mettre à jour ISSO pour lui dire d'accepter les requêtes provenants du domain officiel, maudites CORS :).

Normalement c'est fixé, j'ai fais un commentaire de test dans le dernier SECHebdo avec succès.
