### ISSUE TITLE
Maj page Pantheon

### ISSUE THREAD

**Issue by Astorsoft** [comptoirsecu/csec-hugo#42]
Ajouter les personnes qui contribuent à la correction du site via Github. Reste à voir si il serait pas plus simple de link vers la page github qui liste les contributeurs, au moins ça sera mis á jour dynamiquement

**Comment by SwitHak** [comment]
Deuxième option pour moi. plus simple et ne créé pas de tâches récurrentes en plus.

**Comment by Astorsoft** [comment]
Etant le seul votant tu es majoritaire :D plus sérieusement on va surement se diriger sur quelque chose du style :)
