### ISSUE TITLE
Flux RSS invalid

### ISSUE THREAD

**Issue by jeffmaury** [comptoirsecu/csec-hugo#83]
Podcast Addict me remonte depuis quelques jours des erreurs sur le flux RSS. Cela semble venir de https://www.comptoirsecu.fr/feed/podcast.xml. L'erreur est indiquée en ligne 257

**Comment by newsoft** [comment]
Pareil pour moi [screenshot](https://photos.app.goo.gl/vTgFYYM6sCNYwhAK9).

**Comment by Astorsoft** [comment]
Merci beaucoup pour la notif, j'espère que le problème était récent, quand je vois que la derniere entrée valide dans podcast addict datait d'Avril ça me fait peur...

J'espère que le problème est maintenant réglé pour de bon, hésitez pas à me confirmer =).

**Comment by jeffmaury** [comment]
OK pour moi depuis ce matin et une synchro forcée de PodCast Addict
