### ISSUE TITLE
Corriger les boutons de donation

### ISSUE THREAD

**Issue by Astorsoft** [comptoirsecu/csec-hugo#9]
Pour le moments nos boutons pour faire un don Flattr ou Paypal en bas de page redirigent vers la page d'accueuil.

* Est-il intéressant de garder le bouton Flattr? Ce système est tombé un peu en désuétude et nous ne recevons rien dessus, je serais pour le supprimer
* Il existe semble-t-il un moyen de générer les donations paypals via un lien hypertexte au lieu de leur bouton tout moche https://www.paypal-community.com/t5/About-Business-Archive/Paypal-link-without-using-a-button/td-p/629592 j'ai besoin de quelqu'un avec un acces au paypal *tousse* genre le trésorier *tousse* pour me faire ça :)

**Comment by uZer** [comment]
Hello,
Concernant Flattr, je ne suis pas convaincu de l'utilité réelle, à confirmer avec Justin.
Concernant l'URL de Donation, la voici :
https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=JGQTTJM88SYYC

**Comment by Astorsoft** [comment]
Nickel merci, bon comme vu ensemble on dégage Flattr et on laisse Paypal. A voir si on rajoute un Tipi plus tard.
